---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - metallb_l2advertisement.yaml
  - ocp_ip_pools.yaml

replacements:
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.swift.lb_addresses
    targets:
      - select:
          group: metallb.io
          kind: IPAddressPool
          name: swift
        fieldPaths:
          - spec.addresses
        options:
          create: true

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.swift.iface
    targets:
      - select:
          group: metallb.io
          kind: L2Advertisement
          name: swift
        fieldPaths:
          - spec.interfaces.0
        options:
          create: true
