---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: NetConfig
    patch: |-
      - op: add
        path: /spec/networks/-
        value:
          name: swift
          mtu: 1500
          dnsDomain: _replaced_
          subnets:
            - _replaced_

replacements:
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.swift.dnsDomain
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=swift].dnsDomain
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.swift.subnets
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=swift].subnets
