---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  # Set namespace to OpenStack on all namespaced objects without a namespace
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

resources:
  - ocp_networks_netattach.yaml

replacements:
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.swift.net-attach-def
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: swift
        fieldPaths:
          - spec.config
        options:
          create: true
